### ISSUE TITLE
关于HW3的数据增强

### ISSUE THREAD

**Issue by detect42** [Hoper-J/HUNG-YI_LEE_Machine-Learning_Homework#2]
感觉数据增强应该保留原来的数据并把transform后的数据一并加入数据集，这样从质量和数量上都拓展了数据集，感觉效果会更好？

**Comment by Hoper-J** [comment]
是可以的，但想达到类似目的，可以延长 max_epoch，因为训练的时间其实没有太大的变化，也同样拓展了数据集。

以 max_epoch=1 为例，我们可以提前将 transform 后的数据存储到数据集（离线增强），此时数据量为原来的 2 倍，但在原来的网络中（在线增强）将  max_epoch 设置为 2 一样可以达到类似的效果，因为每次数据进去都会做一次 transform，所以在 2 轮训练完成时，数据集实际上也是被拓展为了原来的 2 倍，这其实和提前拓展为 2 倍然后训练 1 轮的效果类似。

而且在实际应用上，如果数据集很大，离线增强会占去很多的空间。

P.S. 如果离线增强的同时又进行在线增强，那不妨直接进行在线增强。

**Comment by Hoper-J** [comment]
是可以的，但想达到类似目的，可以延长 max_epoch，因为训练的时间其实没有太大的变化，也同样拓展了数据集。

以 max_epoch=1 为例，我们可以提前将 transform 后的数据存储到数据集（离线增强），此时数据量为原来的 2 倍，但在原来的网络中（在线增强）将 max_epoch 设置为 2 一样可以达到类似的效果，因为每次数据进去都会做一次 transform，所以在 2 轮训练完成时，数据集实际上也是被拓展为了原来的 2 倍，这其实和提前拓展为 2 倍然后训练 1 轮的效果类似。

而且在实际应用上，如果数据集很大，离线增强会占去很多的空间。

P.S. 如果离线增强的同时又进行在线增强，那不妨直接进行在线增强。

**Comment by detect42** [comment]
确实是这样，谢谢博主答疑！
